# Generated by Django 3.2.15 on 2022-08-23 20:57

from django.db import migrations, models
import geoposition.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Enter the animals name', max_length=30)),
                ('location', geoposition.fields.GeopositionField(max_length=42)),
            ],
        ),
    ]
