# Generated by Django 3.2.15 on 2022-08-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranchdash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasture',
            name='location',
        ),
        migrations.AddField(
            model_name='pasture',
            name='loc',
            field=models.FloatField(default=1.0),
        ),
    ]
