# Generated by Django 3.2.15 on 2022-08-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranchdash', '0002_auto_20220823_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasture',
            name='max_cows',
            field=models.PositiveSmallIntegerField(default=1, help_text='Maximum number of cows possible in pasture.'),
        ),
    ]
